export enum LFG_SOCKET_CHANNEL {
    USER_JOIN_LOBBY = "USER_JOIN_LOBBY",
    USER_LEAVE_LOBBY = "USER_LEAVE_LOBBY",
    USER_JOINED_LOBBY = "USER_JOINED_LOBBY",
    USER_LEFT_LOBBY = "USER_LEFT_LOBBY"
}