export enum GAME_REQUEST_SOCKET_CHANNEL {
    RECEIVE_GAME_REQUEST = "RECEIVE_GAME_REQUEST",
    SEND_GAME_REQUEST = "SEND_GAME_REQUEST",
    DECLINE_GAME_REQUEST = "DECLINE_GAME_REQUEST",
    CANCEL_GAME_REQUEST = "CANCEL_GAME_REQUEST",
    REMOVE_GAME_REQUEST = "REMOVE_GAME_REQUEST",
}