export enum GAME_REQUEST_SOCKET_CHANNEL {
    RECEIVE_GAME_REQUEST_IN = "RECEIVE_GAME_REQUEST_IN",
    RECEIVE_GAME_REQUEST_OUT = "RECEIVE_GAME_REQUEST_OUT",
    SEND_GAME_REQUEST = "SEND_GAME_REQUEST",
    SENT_GAME_REQUEST = "SEND_GAME_REQUEST",
    DECLINE_GAME_REQUEST = "DECLINE_GAME_REQUEST",
    CANCEL_GAME_REQUEST = "CANCEL_GAME_REQUEST",
    REMOVE_GAME_REQUEST_IN = "REMOVE_GAME_REQUEST_IN",
    REMOVE_GAME_REQUEST_OUT = "REMOVE_GAME_REQUEST_OUT",
    ACCEPT_GAME_REQUEST = "ACCEPT_GAME_REQUEST",
}