"use strict";
exports.__esModule = true;
var GAME_REQUEST_TYPE;
(function (GAME_REQUEST_TYPE) {
    GAME_REQUEST_TYPE["ADD_INCOMING_GAME_REQUEST"] = "ADD_INCOMING_GAME_REQUEST";
    GAME_REQUEST_TYPE["ADD_OUTGOUNG_GAME_REQUEST"] = "ADD_OUTGOUNG_GAME_REQUEST";
    GAME_REQUEST_TYPE["REMOVE_INCOMING_GAME_REQUEST"] = "REMOVE_INCOMING_GAME_REQUEST";
    GAME_REQUEST_TYPE["REMOVE_OUTGOING_GAME_REQUEST"] = "REMOVE_OUTGOUNG_GAME_REQUEST";
})(GAME_REQUEST_TYPE = exports.GAME_REQUEST_TYPE || (exports.GAME_REQUEST_TYPE = {}));
